name: public to gcr

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      project_id:
        required: true
        type: string
      application:
        required: true
        type: string
      project:
        required: true
        type: string
      environment:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      gcloud_service_key:
        required: true
  
jobs:
  build_push:
    name: Build and Push to GCR
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.gcloud_service_key }} # can be base64 encoded or plain text
        registry: ${{ inputs.registry }}
        project_id: ${{ inputs.project_id }}
        image_name: ${{ inputs.application }}-${{ inputs.project }}-${{ inputs.environment }}
        image_tag: latest,${{ inputs.tag }}
        dockerfile: ${{ inputs.dockerfile_path }}